name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Build and Deploy
      uses: solybum/hexo-deploy@master
      env:
        PERSONAL_TOKEN: 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
        PUBLISH_REPOSITORY: Yoichi-Sato482/yoichi-sato482.github.io # The repository the action should deploy to.
        BRANCH: main  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
