name: Hexo Deploy

on:
  push:
    branches:
      - main  # 根据你的主分支名称调整这里

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 根据你的项目需要的 Node.js 版本调整这里

    - name: Install Dependencies
      run: |
        npm install

    - name: Hexo Clean and Generate
      run: |
        npx hexo clean
        npx hexo generate

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'Yoichi-Sato482'
        git config --global user.email 'yoichisato2022@outlook.com'
        git clone --branch=main https://github.com/Yoichi-Sato482/yoichi-sato482.github.io.git .deploy_git
        cp -r public/* .deploy_git
        cd .deploy_git
        git add -A
        git commit -m "Deployed by GitHub Actions"
        git push origin main  # 根据你的仓库设置调整分支名

