name: Hexo Deploy

on:
  push:
    branches:
      - main  # 当 main 分支有更新时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install

      - name: Hexo Clean and Generate
        run: |
          npx hexo clean
          npx hexo generate

      - name: Deploy to Homepage branch in /blog
        run: |
          git config --global user.name 'Yoichi-Sato482'
          git config --global user.email 'yoichisato2022@outlook.com'

          # 克隆 homepage 分支
          git clone -b homepage https://${{ secrets.GH_TOKEN }}@github.com/Yoichi-Sato482/yoichi-sato482.github.io.git .deploy_homepage

          # 将生成的 Hexo 静态文件复制到 /blog 目录
          mkdir -p .deploy_homepage/blog
          cp -r public/* .deploy_homepage/blog
          cd .deploy_homepage

          # 提交更改到 homepage 分支
          git add -A
          git commit -m "Deployed Hexo blog to /blog by GitHub Actions"
          git push origin homepage
